/**
 * Design tokens ported 1:1 from ../premium_canine_wellness/DESIGN.md
 * (the Stitch design-system export). Do not hand-edit values here without
 * updating DESIGN.md as well — this file is the implementation of that spec.
 */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-background': '#001f29',
        error: '#ba1a1a',
        'on-primary-fixed': '#002020',
        'on-secondary-fixed': '#2f1400',
        background: '#f3faff',
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#6f3800',
        surface: '#f3faff',
        'surface-container-high': '#ccedfe',
        'surface-bright': '#f3faff',
        'surface-container-highest': '#c6e8f8',
        'inverse-on-surface': '#dff4ff',
        'primary-container': '#2d6a6a',
        'tertiary-fixed': '#e1e6c2',
        'on-secondary-container': '#783d01',
        'on-error': '#ffffff',
        outline: '#707978',
        tertiary: '#474b31',
        'tertiary-fixed-dim': '#c5c9a7',
        'inverse-surface': '#123441',
        'primary-fixed': '#b1eeed',
        'on-error-container': '#93000a',
        'secondary-fixed': '#ffdcc4',
        'secondary-container': '#ffab69',
        'on-secondary': '#ffffff',
        'surface-variant': '#c6e8f8',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#d8f2ff',
        'primary-fixed-dim': '#95d1d1',
        'outline-variant': '#bfc8c8',
        'on-tertiary-fixed-variant': '#45492f',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#074f4f',
        'tertiary-container': '#5f6347',
        secondary: '#8e4e14',
        'on-primary': '#ffffff',
        'secondary-fixed-dim': '#ffb780',
        'on-primary-container': '#abe8e7',
        'on-surface': '#001f29',
        'on-surface-variant': '#3f4848',
        'on-tertiary-container': '#dbdfbc',
        'surface-dim': '#bedfef',
        'on-tertiary-fixed': '#1a1d07',
        'surface-container-low': '#e6f6ff',
        primary: '#0c5252',
        'surface-tint': '#2a6767',
        'inverse-primary': '#95d1d1',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'max-width': '1200px',
        'margin-mobile': '20px',
        base: '8px',
        gutter: '16px',
        xl: '64px',
        sm: '12px',
        lg: '40px',
        'margin-desktop': 'auto',
        xs: '4px',
        md: '24px',
      },
      fontFamily: {
        'display-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-bold': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-bold': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      boxShadow: {
        soft: '0 4px 20px rgba(0, 31, 41, 0.05)',
      },
    },
  },
  plugins: [],
}
